### ISSUE TITLE
"nav-item border-end" sur mobile

### ISSUE THREAD

**Issue by dobaret** [tomacla/biketeam#153]
Bonjour !

Je me permets de créer cette issue pour un tout petit problème d'interface : en version mobile la classe "border-end" des nav-item _Maps_ et _Home_, ça ne rend pas bien.

![image](https://user-images.githubusercontent.com/91059151/200262770-f9dc1288-c868-4a85-b914-f509792dc55a.png)
![image](https://user-images.githubusercontent.com/91059151/200262796-cdbfe0ca-e469-475c-aef4-9b3561f3826e.png)

Merci pour cette super plateforme et bonne journée !

**Comment by tomacla** [comment]
Corrigé dans le nouveau layout responsive
