### ISSUE TITLE
Possibilité d'avoir les dates-heures format ISO8601

### ISSUE THREAD

**Issue by ashmonger** [tomacla/biketeam#213]
La possibilité d'avoir la notation des dates (dans le menu du choix des rides) au format [ISO8601](https://en.wikipedia.org/wiki/ISO_86010

Comme recommandé dans la [RFC-3339](https://www.rfc-editor.org/rfc/rfc3339#section-5.6https://www.rfc-editor.org/rfc/rfc3339#section-5.6)

Merci

**Comment by glandais** [comment]
Y'a rien qui me choque dans ces méthodes qui sont utilisées systématiquement : https://github.com/tomacla/biketeam/blob/master/src/main/java/info/tomacla/biketeam/common/datatype/Dates.java

**Comment by ashmonger** [comment]
![image](https://github.com/tomacla/biketeam/assets/6398210/0a4d33ff-b94b-4189-8a8f-6f095c2a2bc8)

Les formats de dates/heures en européen siouplé

**Comment by glandais** [comment]
Je dirais que c'est bien fait, ça s'adapte à la locale du navigateur ;)

**Comment by ashmonger** [comment]
My bad...
