### ISSUE TITLE
Ajout fond de carte

### ISSUE THREAD

**Issue by tomacla** [tomacla/biketeam#257]
suppression stamen (payant)
ajout autres fonds à étudier

**Comment by tomacla** [comment]
@mquantin malheureusement ce ne sont pas des layers intégrables. c'est juste une espèce d'image générée par dessus.
et pas d'api documentée en plus

**Comment by mquantin** [comment]
Merci Thomas, 
Zut, 
Oui, c'est pas des tuiles, c'est étrange ce grand png de  couleur en overlay surement généré à la volée avec un geojson obtenu par https://tessadem.com/elevation-api/ (payant cependant)

C'est surement pas autorisé mais l'image est généré par une REST API sans token assez simple: 
https://fr-fr.topographic-map.com/?_path=api.maps.getOverlay&southLatitude=45.40611111111111&westLongitude=3.426944444444445&northLatitude=49.46111111111111&eastLongitude=15.295555555555556&zoom=7
:D
