### ISSUE TITLE
SSO google : 403

### ISSUE THREAD

**Issue by nithwith** [tomacla/biketeam#286]
Hello,

On a un soucis avec le SSO gooe pour un des user sur Kergravoul. Si tu as un moment :)

Pour reproduire : il se connecte a Strava en SSO avec son compte google. Du coup, l'authentification fait Prendslaroue > Strava > Google > 403.

Demande non urgente 

![Screenshot_20240415-204608_Signal](https://github.com/tomacla/biketeam/assets/19471913/f9c99f54-2bbf-40c5-8c87-5727d6c63c5f)

**Comment by tomacla** [comment]
J'ai testé deux flux : 
- prendslaroue -> strava -> google
- prendslaroue -> google
dans les deux cas je suis connecté sans soucis.
Donc je sais pas trop j'ai l'impression que c'est plutot un probème lié à l'utilisateur
