### ISSUE TITLE
2 soucis dans gpx2web

### ISSUE THREAD

**Issue by tomacla** [tomacla/biketeam#290]
escaper le nom des GPX avec un CDATA

la librairie part en vrille quand le gpx est trop long à parser => encapsuler ca avec un timeout serait pas mal.

**Comment by tomacla** [comment]
Java heap space error sur : this.gpxPerSecond.computeOnePointPerSecond(gpxPath);

**Comment by glandais** [comment]
T'as un exemple de GPX avec du CDATA ?

**Comment by tomacla** [comment]
faut juste que tu mettes ca pour le nom de la track

`<name><![CDATA[nom avec plein de caractères bizarre & < > "" "]]></name>`

**Comment by glandais** [comment]
![image](https://github.com/tomacla/biketeam/assets/864152/e81e4bd9-15c8-4ce4-86c1-7a162f5a3369)
J'arrive pas à reproduire

**Comment by glandais** [comment]
C'est OK ! Faut réuploader la map cependant

**Comment by tomacla** [comment]
OK.
J'ai réparé à la main les maps avec le caractères "&". Le caractère ">" avait l'air de passer malgré le fait que le fichier devenait corrompu par d'autres outils.
Dans tous les cas c'est plus propre comme ca
