### ISSUE TITLE
Problème d'affichage des distances sur le profil de carte

### ISSUE THREAD

**Issue by ashmonger** [tomacla/biketeam#299]
![image](https://github.com/tomacla/biketeam/assets/6398210/67f5e1bb-06e2-493c-bcda-1da93aa72cbb)
![image](https://github.com/tomacla/biketeam/assets/6398210/7cb3fd5a-c319-4c8b-aa74-3e9d4e1272f9)

**Comment by glandais** [comment]
Corrigé avec #301
