### ISSUE TITLE
Page Maps - 2 nouveaux critères de recherche

### ISSUE THREAD

**Issue by BaptisteDhuvettere** [tomacla/biketeam#30]
En tant que "cycliste" je veux pouvoir filtrer les maps par :

* Type (route, gravel, VTT)

* Dénivelé sous la forme "De"  "A" (en mètres)
Filtre sur le champs qui donne le D+

Merci :)

**Comment by tomacla** [comment]
Doublon https://github.com/tomacla/biketeam/issues/21
