### ISSUE TITLE
Feature : dindon 

### ISSUE THREAD

**Issue by 6rus** [tomacla/biketeam#5]
Dans index : 
` <script src="/js/ee.js"></script>`
Contenu du fichier /js/ee.js
`
var shakeEvent = new Shake({ threshold: 5 });
shakeEvent.start();
window.addEventListener('shake', function () {
    var audio = new Audio('/ee.mp3');
    audio.play();
}, false);
`

**Comment by glandais** [comment]
As a user, I want to be a turkey
