### ISSUE TITLE
Pouvoir ajouter plusieurs maps à un ride

### ISSUE THREAD

**Issue by fab33** [tomacla/biketeam#77]
C'est possible de le faire en faisant plusieurs groupes mais on ne peut rejoindre qu'un seul groupe.
Notre utilité serait sur un ride de plusieurs jours avec des étapes.

**Comment by tomacla** [comment]
Oui effectivement c'est un bon cas d'utilisation. Je vais regarder ca dès que j'aurai un peu de temps.
